# Generated by Django 5.0.4 on 2024-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
