# Generated by Django 5.0.4 on 2024-05-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_reviews',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='control_core.carreview'),
        ),
    ]
