# Generated by Django 5.0.4 on 2024-05-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0002_alter_car_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='control_core.car'),
        ),
    ]
