# Generated by Django 5.0.4 on 2024-05-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_days',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='rent_car_by_user',
        ),
        migrations.AddField(
            model_name='orders',
            name='rent_car_by_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='car_orders', to='control_core.car'),
        ),
    ]
