# Generated by Django 5.0.4 on 2024-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0005_alter_orders_rent_car_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_reviews',
        ),
        migrations.AddField(
            model_name='car',
            name='reviews',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
