# Generated by Django 5.0.4 on 2024-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0006_remove_car_car_reviews_car_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reviews',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=5),
        ),
    ]
