# Generated by Django 5.0.4 on 2024-05-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0008_alter_car_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='rent_end_from',
        ),
        migrations.RemoveField(
            model_name='carrent',
            name='rent_start_from',
        ),
    ]
