# Generated by Django 5.0.4 on 2024-05-25 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_core', '0009_remove_carrent_rent_end_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='rental_start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
