# Generated by Django 5.0.4 on 2024-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(db_index=True, default='', max_length=100)),
                ('last_name', models.CharField(db_index=True, default='', max_length=100)),
                ('nationality', models.CharField(db_index=True, default='', max_length=100)),
                ('payment_method', models.CharField(db_index=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('password', models.CharField(db_index=True, default=None, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
