# Generated by Django 5.0.4 on 2024-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
