# Generated by Django 5.0.4 on 2024-05-25 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_account', '0003_user_full_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default='', max_length=100)),
                ('nationality', models.CharField(db_index=True, default='', max_length=100)),
                ('payment_method', models.CharField(db_index=True, default='', max_length=100)),
                ('date_ordered', models.DateField(db_index=True, default='')),
                ('phone_no', models.CharField(db_index=True, default='', max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
