# Generated by Django 5.0.4 on 2024-05-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_account', '0004_remove_user_full_name_remove_user_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='payment_method',
        ),
    ]
