# Generated by Django 5.0.4 on 2024-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_account', '0005_remove_personaldetails_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='date_ordered',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
